import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ fontSize: 30 }}>
        macedo<span style={{ fontWeight: 400, fontSize: 30 }}>mauriz</span>
      </h1>
      <h2>about</h2>
    </>
  );
}
