import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      macedo<span style={{ fontWeight: 400, fontSize: 30 }}>mauriz</span>
      <h2>about</h2>
    </>
  )
}
