import Head from "next/head"
// import Image from "next/image";
// import dynamic from "next/dynamic"

export default function Home() {
  return (
    <>
      <Head>
        <title>Web developer | Rodrigo Macedo</title>
        <link rel="canonical" href="https://macedomauriz.com" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      content
    </>
  )
}
