import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import { Avatar, Pagination } from "@nextui-org/react";

const CustomCheckbox = dynamic(() => import("../components/Checkbox"));
const CustomTable = dynamic(() => import("../components/Table"));
const CustomCollapse = dynamic(() => import("../components/Collapse"));

export default function Home() {
  return (
    <>
      <Head>
        <title>NextUI Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ fontSize: 30 }}>
        macedo<span style={{ fontWeight: 400, fontSize: 30 }}>mauriz</span>
      </h1>
    </>
  );
}
