---
# name: Build and deploy site to AWS CloudFront
#
# on:
#   push:
#     branches: [master]
#
# jobs:
#   build-and-deploy:
#     name: Build and deploy
#     runs-on: ubuntu-latest
#     env:
#       BUCKET: macedomauriz.com
#       DIST: out
#       REGION: us-west-1
#       DIST_ID: EAEQCK2VGFN8X
#
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
#           aws-region: ${{ env.REGION }}
#
#       - name: Install dependencies
#         run: |
#           node --version
#           npm ci
#
#       - name: Build
#         run: npm run build
#
#       - name: Copy files to production with AWS CLI
#         run: |
#           aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}
#
#       - name: Copy files to production with AWS CLI
#         run: |
#           aws cloudfront create-invalidation \
#             --distribution-id ${{ env.DIST_ID }} \
#             --paths "/*"

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  AWS_REGION: us-west-1 #Change to reflect your Region

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::296727581481:role/GithubActions-macedomauriz.com
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
