---
name: Build and deploy site to AWS CloudFront
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: macedomauriz.com
      DIST: out
      REGION: us-west-1
      DIST_ID: EAEQCK2VGFN8X

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ env.REGION }}

      - name: Install dependencies
        run: |
          node --version
          npm ci

      - name: Build
        run: npm run build

      - name: Copy files to production with AWS CLI
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: Copy files to production with AWS CLI
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
